apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}-allow-egress  
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.appName }}
  egress:
  - to:
    ports:
    - protocol: TCP
      port: 53 
    ports:
    - protocol: UDP
      port: 53  
    - podSelector:
        matchLabels:
          app: postgres