apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}-allow-ingress  
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.appName }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{.Values.servingAppName }}