apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.appName }}-clusterrole
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
